---
driver_plugin: openstack
driver_config:
  name: openstack
  openstack_username: "<%= ENV['KITCHEN_OS_USERNAME'] %>"
  openstack_api_key: "<%= ENV['KITCHEN_OS_PASSWORD'] %>"
  openstack_auth_url: "<%= ENV['KITCHEN_OS_AUTH_URL'] %>"
  openstack_identity_endpoint: "<%= ENV['KITCHEN_OS_AUTH_URL'] %>"
  openstack_tenant: "<%= ENV['KITCHEN_OS_TENANT_NAME'] %>"
  key_name: "<%= ENV['KITCHEN_OS_KEY_NAME'] %>"
  private_key_path: "<%= ENV['PWD'] %>/.kitchen.key"
  floating_ip_pool: "<%= ENV['KITCHEN_OS_FLOATING_IP_POOL'] %>"
  flavor_ref: "<%= ENV['KITCHEN_OS_FLV_1_vCPU_RAM_1G'] %>"
  username: stack

platforms:
  - name: ubuntu-12.04
    driver_config:
      image_ref: <%= ENV['KITCHEN_OS_IMG_UBUNTU1204'] %>

suites:
  - name: 'default'
    run_list:
      - recipe[fake-ndenv::user]
      - recipe[ndenv]
      - recipe[ndenv::install]
      - recipe[fake-ndenv]
    attributes:
      ndenv:
        group_users: [ test-user ]
        installs:
          - 0.10.20
          - 0.10.26
        global: 0.10.20
